# Generated by Django 4.0.4 on 2022-05-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biryani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biryanidb',
            name='does_akhila_like',
            field=models.BooleanField(choices=[('YES', True), ('NO', False)], default=False, max_length=3),
            preserve_default=False,
        ),
    ]
