# Generated by Django 4.0.4 on 2022-05-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biryani', '0002_biryanidb_does_akhila_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biryanidb',
            name='id',
        ),
        migrations.AlterField(
            model_name='biryanidb',
            name='biryani_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
