# Generated by Django 4.0.4 on 2024-05-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biryani', '0006_alter_biryanidb_does_akhila_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biryanidb',
            name='does_akhila_like',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], max_length=3),
        ),
    ]
